server:
  port: 8080
  servlet:
    context-path: /api/v1
--- #################### 数据库相关配置 ####################
spring:
  # 数据源配置项
  datasource:
    name: home
    url: jdbc:postgresql://localhost:15432/${spring.datasource.name}?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  # ============= JPA 配置 ============= #
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false